name: MCP Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install
        working-directory: ./backend

      - name: 🧪 Run tests (optional - update test command if needed)
        run: npm test || echo "⚠️ No tests found"
        working-directory: ./backend

      - name: 🐳 Build Docker image
        run: docker build -t mcp-backend .
        working-directory: ./backend

      # ⬇️ OPTIONAL: Push Docker image to Docker Hub or GitHub Container Registry
      # - name: 📤 Push Docker image
      #   run: |
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
   
